version: '3'

services:
  origin_server:
    build: nodejs-media-server
    ports:
      - "4312:4312"
  nginx_cache_1:
    build: nginx-internal-caching
    depends_on:
      - origin_server
    ports:
      - "83:80"
      - "84:82"
  nginx_cache_2:
    build: nginx-internal-caching
    depends_on:
      - origin_server
    ports:
      - "85:80"
      - "86:82"
  nginx_cache_3:
    build: nginx-internal-caching
    depends_on:
      - origin_server
    ports:
      - "87:80"
      - "88:82"
