global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels: {monitor: my-project}
rule_files: [alert.rules]
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: ['alertmanager:9093']
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets: ['localhost:9090']
- job_name: cadvisor
  scrape_interval: 5s
  dns_sd_configs:
  - names: [tasks.cadvisor]
    type: A
    port: 8080
  static_configs:
  - targets: ['cadvisor:8080']
- job_name: node
  scrape_interval: 15s
  static_configs:
  - targets: ['192.168.161.161:9100', '192.168.161.165:9100', '192.168.161.164:9100',
      '10.147.65.145:9100', '10.147.65.145:9100', '10.147.65.145:9100', '10.147.65.145:9100',
      '10.147.65.145:9100', '10.120.30.10:9100']
