version: '3'

volumes:
  prometheus_data: {}

services:
  nfvo:
    image: openbaton/nfvo:latest
    depends_on:
      - rabbitmq_broker
      - nfvo_database
    restart: always
    environment:
      - NFVO_RABBIT_BROKERIP=${HOST_IP} # for use in userdata.sh in vnfm-generic
      - NFVO_MONITORING_IP=${ZABBIX_IP}
      - NFVO_PLUGIN_INSTALLATION-DIR=/dev/null
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
      - SPRING_DATASOURCE_URL=jdbc:mysql://nfvo_database:3306/openbaton
      - SPRING_DATASOURCE_DRIVER-CLASS-NAME=org.mariadb.jdbc.Driver
      - SPRING_JPA_DATABASE-PLATFORM=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_HIBERNATE_DDL-AUTO=update
    ports:
      - "8080:8080"
  vnfm-generic:
    image: openbaton/vnfm-generic:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - VNFM_RABBITMQ_BROKERIP=rabbitmq_broker
  vnfm-dummy-amqp:
    image: openbaton/vnfm-dummy-amqp:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
  plugin-vimdriver-test:
    image: openbaton/plugin-vimdriver-test:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - RABBITMQ=rabbitmq_broker
  plugin-vimdriver-openstack-4j:
    image: openbaton/plugin-vimdriver-openstack-4j:latest
    depends_on:
      - nfvo
    restart: always
    environment:
      - RABBITMQ=rabbitmq_broker
  nfvo_database:
    image: mysql/mysql-server
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_DATABASE=openbaton
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=changeme
    volumes:
      - ./dbdata_nfvo:/var/lib/mysql
  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    hostname: openbaton-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=openbaton
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./dbdata_rabbit:/var/lib/rabbitmq
  prometheus:
    image: prom/prometheus:v2.0.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    restart: always
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}

  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command: 
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100
    restart: always
    deploy:
      mode: global
  cadvisor:
    image: google/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    ports:
      - 8081:8080
    restart: always
    deploy:
      mode: global
