version: '2'

services:
  nfvo:
    image: openbaton/nfvo:5.0.0
    depends_on:
      - rabbitmq_broker
    restart: always
    environment: 
      - NFVO_RABBIT_BROKERIP=localhost
      - NFVO_PLUGIN_INSTALLATION-DIR=/
      - SPRING_RABBITMQ_HOST=rabbitmq_broker
    ports:
      - "8080:8080"
    expose:
      - 8080
  rabbitmq_broker:
    image: rabbitmq:3-management-alpine
    hostname: openbaton-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=openbaton
    ports:
      - "5672:5672"
      - "15672:15672"
    expose:
      - 5672
      - 15672
  prometheus:
   image: prom/prometheus
   ports:
     - "9090:9090"
   expose:
     - 9090
   volumes:
     - "/home/radoslav/projects/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
