version: '3'

services:
  nginx_cache_1:
    build: cache-tier
    ports:
      - "83:80"
      - "84:82"
  nginx_cache_2:
    build: cache-tier
    ports:
      - "85:80"
      - "86:82"
  nginx_cache_3:
    build: cache-tier
    ports:
      - "87:80"
      - "88:82"
  nginx_lb:
    build: lb-tier
    depends_on:
      - nginx_cache_3
      - nginx_cache_2
      - nginx_cache_1
    ports:
      - "89:82"
